Added basic demo project
nstack-io/nstack-ios-sdk pull request #72
Opened 2020-10-15 10:53 UTC by mariusc

- Added demo project showing an example of using localizations

2020-10-17 09:54 UTC, jakobmygind commented on Documentation/NStack 5.0 Migration Guide.md
> +         let appConfig = AppConfiguration()
Hi @mariusc Unless `AppConfiguration` is an integral part of the sdk (which it doesn't seem like?) I feel this line adds more confusion than clarity by making assumptions about client code structure, so the keys for the sake of clarity might just be hardcoded or replaced by `<your plist filename here>` or something.

2020-10-19 06:53 UTC, mariusc commented on Documentation/NStack 5.0 Migration Guide.md
> +         let appConfig = AppConfiguration()
Makes sense; it was a copy-paste from an actual project where I did the migration, and I think it is part of the stuff that's generated by the template project generator, but I agree that in this context it creates more confusion; I'll update the document

2020-11-10 14:49 UTC, chriscombs requested changes

2020-11-10 14:49 UTC, chriscombs commented on NStackDemo/App/AppDelegate.swift
> +        nstackConfig.updateOptions = [.onDidBecomeActive]
I think we should remove this line, the demo project should show default behavior as much as possible

2020-11-19 12:06 UTC, chriscombs approved these changes

2020-11-20 07:13 UTC, merged